---
version: "3.8"

services:
  base:
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_DIR}/base-${PROJECT_NAME}:${IMAGE_TAG}
    container_name: base-${PROJECT_NAME}
    build:
      target: base
      context: .
      args:
        - DOCKER_VERSION=${DOCKER_VERSION}
  base_ansible:
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_DIR}/base-${PROJECT_NAME}-ansible:${IMAGE_TAG}
    container_name: base-ansible-${PROJECT_NAME}
    build:
      target: base-ansible
      context: .
      args:
        - DOCKER_VERSION=${DOCKER_VERSION}
        - HADOLINT_VERSION=${HADOLINT_VERSION}
